### ISSUE TITLE
Confirm Order Button Missing

### ISSUE THREAD

**Issue by devdiginest** [cashfree/cashfree-opencart-kit#2]
Confirm Order Button missing after enabling cash free payment method. We use single-page checkout for the checkout page.

**Comment by prem-cashfree** [comment]
@devdiginest  As you one page checkout is a paid extension and it create a theme inside the project. As a payment aggregator we built our extension on default theme. So issue with the file path only. So just change the file path in controller and if required move catalog payment theme file too as per your theme.
